"""
Obsidian Review Stats Handler

Dual-saves review stats to Obsidian markdown table via GitHub API.
Single file: 98. 数据库/02. Review Stats/Review_Stats.md

Each row is one day: Date | Reviewed | Again | Good | Easy
"""

import os
import re
import base64
import logging
import aiohttp
from datetime import datetime

logger = logging.getLogger(__name__)

GITHUB_API = "https://api.github.com"
REPO = "NotebookOfCCC/Obsidian"
FILE_PATH = "98. 数据库/02. Review Stats/Review_Stats.md"
MAX_RETRIES = 3

FILE_HEADER = """# Review Stats

> Auto-generated by Review Bot. Each day's review counts are saved to both Notion and this file.

| Date | Reviewed | Again | Good | Easy |
|------|----------|-------|------|------|
"""


class ObsidianReviewStatsHandler:
    def __init__(self):
        self.token = os.getenv("OBSIDIAN_GITHUB_TOKEN")
        if not self.token:
            raise ValueError("OBSIDIAN_GITHUB_TOKEN not set")
        self.headers = {
            "Authorization": f"token {self.token}",
            "Accept": "application/vnd.github.v3+json",
        }
        self._sha_cache = {}

    async def _get_file(self, filepath: str) -> tuple[str, str]:
        """Fetch file content and SHA from GitHub."""
        url = f"{GITHUB_API}/repos/{REPO}/contents/{filepath}"
        async with aiohttp.ClientSession() as session:
            async with session.get(url, headers=self.headers) as resp:
                if resp.status == 404:
                    raise FileNotFoundError(f"File not found: {filepath}")
                if resp.status != 200:
                    text = await resp.text()
                    raise Exception(f"GitHub API error {resp.status}: {text}")
                data = await resp.json()
                content = base64.b64decode(data["content"]).decode("utf-8")
                sha = data["sha"]
                self._sha_cache[filepath] = sha
                return content, sha

    async def _put_file(self, filepath: str, content: str, message: str):
        """Write file content to GitHub with conflict retry."""
        for attempt in range(MAX_RETRIES):
            url = f"{GITHUB_API}/repos/{REPO}/contents/{filepath}"
            sha = self._sha_cache.get(filepath)
            if not sha:
                try:
                    _, sha = await self._get_file(filepath)
                except FileNotFoundError:
                    sha = None

            encoded = base64.b64encode(content.encode("utf-8")).decode("utf-8")
            payload = {"message": message, "content": encoded}
            if sha:
                payload["sha"] = sha

            async with aiohttp.ClientSession() as session:
                async with session.put(url, headers=self.headers, json=payload) as resp:
                    if resp.status in (200, 201):
                        data = await resp.json()
                        self._sha_cache[filepath] = data["content"]["sha"]
                        logger.info(f"Updated {filepath} on GitHub")
                        return
                    elif resp.status == 409 and attempt < MAX_RETRIES - 1:
                        logger.warning(f"Conflict on {filepath}, retrying (attempt {attempt + 1})")
                        self._sha_cache.pop(filepath, None)
                        continue
                    else:
                        text = await resp.text()
                        raise Exception(f"GitHub write error {resp.status}: {text}")

    def _parse_rows(self, content: str) -> dict[str, dict]:
        """Parse markdown table into {date_str: {reviewed, again, good, easy}}."""
        rows = {}
        for line in content.strip().split("\n"):
            line = line.strip()
            if not line.startswith("|") or line.startswith("|---") or line.startswith("| Date"):
                continue
            cells = [c.strip() for c in line.split("|")]
            # cells[0] is empty (before first |), cells[-1] is empty (after last |)
            cells = [c for c in cells if c]
            if len(cells) >= 5:
                date_str = cells[0]
                if re.match(r"\d{4}-\d{2}-\d{2}", date_str):
                    rows[date_str] = {
                        "reviewed": int(cells[1]) if cells[1].isdigit() else 0,
                        "again": int(cells[2]) if cells[2].isdigit() else 0,
                        "good": int(cells[3]) if cells[3].isdigit() else 0,
                        "easy": int(cells[4]) if cells[4].isdigit() else 0,
                    }
        return rows

    def _build_content(self, rows: dict[str, dict]) -> str:
        """Rebuild the full markdown file from rows dict."""
        content = FILE_HEADER
        for date_str in sorted(rows.keys()):
            r = rows[date_str]
            content += f"| {date_str} | {r['reviewed']} | {r['again']} | {r['good']} | {r['easy']} |\n"
        return content

    async def record_review(self, response: str, date_str: str = None):
        """Increment today's counter for the given response type in Obsidian.

        Args:
            response: "again", "good", or "easy"
            date_str: optional date override (YYYY-MM-DD), defaults to today
        """
        if not date_str:
            import zoneinfo
            tz = os.getenv("TIMEZONE", "Europe/London")
            date_str = datetime.now(zoneinfo.ZoneInfo(tz)).date().isoformat()

        try:
            content, _ = await self._get_file(FILE_PATH)
        except FileNotFoundError:
            content = FILE_HEADER

        rows = self._parse_rows(content)

        if date_str not in rows:
            rows[date_str] = {"reviewed": 0, "again": 0, "good": 0, "easy": 0}

        rows[date_str]["reviewed"] += 1
        rows[date_str][response] = rows[date_str].get(response, 0) + 1

        new_content = self._build_content(rows)
        await self._put_file(FILE_PATH, new_content, f"review-stats: {date_str} +1 {response}")

    async def bulk_upsert(self, stats_list: list[dict]):
        """Bulk write stats rows (for migration). Each dict: {date, reviewed, again, good, easy}.

        Overwrites existing rows for the same date.
        """
        try:
            content, _ = await self._get_file(FILE_PATH)
        except FileNotFoundError:
            content = FILE_HEADER

        rows = self._parse_rows(content)

        for s in stats_list:
            rows[s["date"]] = {
                "reviewed": s.get("reviewed", 0),
                "again": s.get("again", 0),
                "good": s.get("good", 0),
                "easy": s.get("easy", 0),
            }

        new_content = self._build_content(rows)
        await self._put_file(FILE_PATH, new_content, f"review-stats: bulk upsert {len(stats_list)} days")
        logger.info(f"Bulk upserted {len(stats_list)} days to Obsidian review stats")
