"""
Obsidian Vocabulary Handler

Appends vocab entries to Obsidian markdown table files via GitHub API.
Auto-creates new files every 1000 entries.

Reuses the same GitHub API pattern as github_handler.py.
"""

import os
import re
import base64
import logging
import aiohttp
from datetime import datetime

logger = logging.getLogger(__name__)

GITHUB_API = "https://api.github.com"
REPO = "NotebookOfCCC/Obsidian-Database"
BASE_PATH = "02. 数据库/01. Vocabulary Telegram"
MAX_ENTRIES_PER_FILE = 1000
MAX_RETRIES = 3

FILE_HEADER = """# Vocabulary Database - Part {part}

> Auto-generated by Vocab Bot. Each entry is saved to both Notion and this file.
> New file created automatically every 1000 entries.

| # | English | Chinese | Explanation | Example EN | Example ZH | Category | Date |
|---|---------|---------|-------------|------------|------------|----------|------|
"""


class ObsidianVocabHandler:
    BASE_PATH = BASE_PATH

    def __init__(self):
        self.token = os.getenv("OBSIDIAN_GITHUB_TOKEN")
        if not self.token:
            raise ValueError("OBSIDIAN_GITHUB_TOKEN not set")
        self.headers = {
            "Authorization": f"token {self.token}",
            "Accept": "application/vnd.github.v3+json",
        }
        self._sha_cache = {}

    async def _get_file(self, filepath: str) -> tuple[str, str]:
        """Fetch file content and SHA from GitHub."""
        url = f"{GITHUB_API}/repos/{REPO}/contents/{filepath}"
        async with aiohttp.ClientSession() as session:
            async with session.get(url, headers=self.headers) as resp:
                if resp.status == 404:
                    raise FileNotFoundError(f"File not found: {filepath}")
                if resp.status != 200:
                    text = await resp.text()
                    raise Exception(f"GitHub API error {resp.status}: {text}")
                data = await resp.json()
                content = base64.b64decode(data["content"]).decode("utf-8")
                sha = data["sha"]
                self._sha_cache[filepath] = sha
                return content, sha

    async def _put_file(self, filepath: str, content: str, message: str):
        """Write file content to GitHub with conflict retry."""
        for attempt in range(MAX_RETRIES):
            url = f"{GITHUB_API}/repos/{REPO}/contents/{filepath}"
            sha = self._sha_cache.get(filepath)
            if not sha:
                try:
                    _, sha = await self._get_file(filepath)
                except FileNotFoundError:
                    sha = None

            encoded = base64.b64encode(content.encode("utf-8")).decode("utf-8")
            payload = {"message": message, "content": encoded}
            if sha:
                payload["sha"] = sha

            async with aiohttp.ClientSession() as session:
                async with session.put(url, headers=self.headers, json=payload) as resp:
                    if resp.status in (200, 201):
                        data = await resp.json()
                        self._sha_cache[filepath] = data["content"]["sha"]
                        logger.info(f"Updated {filepath} on GitHub")
                        return
                    elif resp.status == 409 and attempt < MAX_RETRIES - 1:
                        logger.warning(f"Conflict on {filepath}, retrying (attempt {attempt + 1})")
                        self._sha_cache.pop(filepath, None)
                        continue
                    else:
                        text = await resp.text()
                        raise Exception(f"GitHub write error {resp.status}: {text}")

    async def _list_vocab_files(self) -> list[str]:
        """List all Vocabulary_NNN.md files in the repo folder."""
        url = f"{GITHUB_API}/repos/{REPO}/contents/{BASE_PATH}"
        async with aiohttp.ClientSession() as session:
            async with session.get(url, headers=self.headers) as resp:
                if resp.status == 404:
                    return []
                if resp.status != 200:
                    return []
                data = await resp.json()
                files = [
                    item["name"] for item in data
                    if item["type"] == "file" and re.match(r"Vocabulary_\d+\.md$", item["name"])
                ]
                return sorted(files)

    def _count_table_rows(self, content: str) -> int:
        """Count data rows in the markdown table (excluding header and separator)."""
        count = 0
        for line in content.strip().split("\n"):
            line = line.strip()
            if line.startswith("|") and not line.startswith("|---") and not line.startswith("| #"):
                count += 1
        return count

    @staticmethod
    def _extract_base_word(english_field: str) -> str:
        """Extract base word/phrase from english field, stripping IPA and POS."""
        text = english_field.strip()
        # Also unescape pipe chars from markdown table cells
        text = text.replace("\\|", "|")
        # Cut at first '/' (start of IPA) or '(' (start of POS)
        for delimiter in ['/', '(']:
            idx = text.find(delimiter)
            if idx > 0:
                text = text[:idx]
                break
        return text.strip().lower()

    @staticmethod
    def _escape_cell(text: str) -> str:
        """Escape pipe and newline characters for markdown table cells."""
        if not text:
            return ""
        return text.replace("|", "\\|").replace("\n", " <br> ")

    def _entry_to_row(self, entry: dict, row_num: int) -> str:
        """Convert a vocab entry dict to a markdown table row."""
        english = self._escape_cell(entry.get("english", ""))
        chinese = self._escape_cell(entry.get("chinese", ""))
        explanation = self._escape_cell(entry.get("explanation", ""))
        example_en = self._escape_cell(entry.get("example_en", ""))
        example_zh = self._escape_cell(entry.get("example_zh", ""))
        category = self._escape_cell(entry.get("category", "其他"))
        date_str = entry.get("date", datetime.now().strftime("%Y-%m-%d"))
        return f"| {row_num} | {english} | {chinese} | {explanation} | {example_en} | {example_zh} | {category} | {date_str} |"

    async def append_entry(self, entry: dict):
        """
        Append a vocab entry to the current Obsidian markdown file.
        Files 001-004 are historical (one per Notion database), not touched.
        New entries go to 005+, auto-split at MAX_ENTRIES_PER_FILE.
        """
        files = await self._list_vocab_files()

        # Filter to only 005+ files (001-004 are historical imports)
        active_files = [f for f in files if re.search(r"Vocabulary_(\d+)\.md$", f) and int(re.search(r"(\d+)", f).group()) >= 5]

        if not active_files:
            current_file = "Vocabulary_005.md"
            content = FILE_HEADER.format(part=5)
            row_count = 0
        else:
            current_file = active_files[-1]
            filepath = f"{BASE_PATH}/{current_file}"
            content, _ = await self._get_file(filepath)
            row_count = self._count_table_rows(content)

        # Check if we need a new file
        if row_count >= MAX_ENTRIES_PER_FILE:
            match = re.search(r"Vocabulary_(\d+)\.md$", current_file)
            part = int(match.group(1)) + 1 if match else len(files) + 1
            current_file = f"Vocabulary_{part:03d}.md"
            content = FILE_HEADER.format(part=part)
            row_count = 0

        # Append the new row
        new_row = self._entry_to_row(entry, row_count + 1)
        content = content.rstrip("\n") + "\n" + new_row + "\n"

        filepath = f"{BASE_PATH}/{current_file}"
        ts = datetime.now().strftime("%Y-%m-%d %H:%M")
        english = entry.get("english", "unknown")
        await self._put_file(filepath, content, f"vocab-bot: add '{english}' ({ts})")
        logger.info(f"Saved '{english}' to Obsidian: {current_file} (row {row_count + 1})")

    async def replace_entry(self, entry: dict):
        """
        Replace an existing row matching the entry's english word in Obsidian.
        Searches all vocab files (001+). Falls back to append_entry if not found.
        """
        target_word = self._extract_base_word(entry.get("english", ""))
        if not target_word:
            await self.append_entry(entry)
            return

        files = await self._list_vocab_files()
        # Search newest first — most likely to find recent entries faster
        for filename in reversed(files):
            filepath = f"{BASE_PATH}/{filename}"
            try:
                content, _ = await self._get_file(filepath)
            except FileNotFoundError:
                continue

            lines = content.split("\n")
            replaced = False
            for i, line in enumerate(lines):
                stripped = line.strip()
                if not stripped.startswith("|") or stripped.startswith("|---") or stripped.startswith("| #"):
                    continue
                # Split by unescaped pipes
                cells = re.split(r'(?<!\\)\|', stripped)
                if len(cells) < 3:
                    continue
                row_english = cells[2].strip()  # Column 2 is English
                row_word = self._extract_base_word(row_english)
                if row_word == target_word:
                    # Keep existing row number
                    try:
                        row_num = int(cells[1].strip())
                    except (ValueError, IndexError):
                        row_num = 1
                    lines[i] = self._entry_to_row(entry, row_num)
                    replaced = True
                    break

            if replaced:
                new_content = "\n".join(lines)
                ts = datetime.now().strftime("%Y-%m-%d %H:%M")
                english = entry.get("english", "unknown")
                await self._put_file(filepath, new_content, f"vocab-bot: replace '{english}' ({ts})")
                logger.info(f"Replaced '{english}' in Obsidian: {filename}")
                return

        # Not found in any file — fall back to append
        await self.append_entry(entry)
